name: sheshield
description: She Shield – Smart Safety Bracelet. A Flutter app for emergency SOS alerts and GPS location sharing.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.8.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.2
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  permission_handler: ^11.3.0
  url_launcher: ^6.2.4
  firebase_messaging: ^15.2.1
  http: ^1.2.0
  flutter_bluetooth_serial_ble: ^0.5.0
  speech_to_text: ^7.0.0
  camera: ^0.11.0+2
  camera_android: ^0.10.10
  firebase_storage: ^12.4.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
